//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8806
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8806.
// 
namespace CarpetCleaningClient.CarpetCleaningWebService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://192.168.80.10/CARPETCLEANINGWEBSERVICE/WebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDBConnection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CheckDBConnection() {
            object[] results = this.Invoke("CheckDBConnection", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckDBConnection(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckDBConnection", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndCheckDBConnection(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BinitemsQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBinItemsQty[] BinitemsQty(string criteria, string sortcriteria) {
            object[] results = this.Invoke("BinitemsQty", new object[] {
                        criteria,
                        sortcriteria});
            return ((TWmsBinItemsQty[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBinitemsQty(string criteria, string sortcriteria, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BinitemsQty", new object[] {
                        criteria,
                        sortcriteria}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBinItemsQty[] EndBinitemsQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBinItemsQty[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BinitemsQtyUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long BinitemsQtyUpdate(TWmsBinItemsQty binitemqtyrecord) {
            object[] results = this.Invoke("BinitemsQtyUpdate", new object[] {
                        binitemqtyrecord});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBinitemsQtyUpdate(TWmsBinItemsQty binitemqtyrecord, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BinitemsQtyUpdate", new object[] {
                        binitemqtyrecord}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndBinitemsQtyUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertBinTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long InsertBinTrans(TWmsBinItemsQty mbintrans) {
            object[] results = this.Invoke("InsertBinTrans", new object[] {
                        mbintrans});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertBinTrans(TWmsBinItemsQty mbintrans, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertBinTrans", new object[] {
                        mbintrans}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndInsertBinTrans(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BinIDByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long BinIDByCode(short branchid, string bincode) {
            object[] results = this.Invoke("BinIDByCode", new object[] {
                        branchid,
                        bincode});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBinIDByCode(short branchid, string bincode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BinIDByCode", new object[] {
                        branchid,
                        bincode}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndBinIDByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderDetailStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long UpdateOrderDetailStatus(long orderdtlid, short status) {
            object[] results = this.Invoke("UpdateOrderDetailStatus", new object[] {
                        orderdtlid,
                        status});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateOrderDetailStatus(long orderdtlid, short status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateOrderDetailStatus", new object[] {
                        orderdtlid,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndUpdateOrderDetailStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrderDetailItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long UpdateOrderDetailItem(long orderdtlid, long newitemid) {
            object[] results = this.Invoke("UpdateOrderDetailItem", new object[] {
                        orderdtlid,
                        newitemid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateOrderDetailItem(long orderdtlid, long newitemid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateOrderDetailItem", new object[] {
                        orderdtlid,
                        newitemid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndUpdateOrderDetailItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long DeleteReceive(long orderdtlid, int transtype) {
            object[] results = this.Invoke("DeleteReceive", new object[] {
                        orderdtlid,
                        transtype});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteReceive(long orderdtlid, int transtype, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteReceive", new object[] {
                        orderdtlid,
                        transtype}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndDeleteReceive(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBinInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBins GetBinInfo(long binid) {
            object[] results = this.Invoke("GetBinInfo", new object[] {
                        binid});
            return ((TWmsBins)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBinInfo(long binid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBinInfo", new object[] {
                        binid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBins EndGetBinInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBins)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBinInfoByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBins GetBinInfoByCode(string bincode) {
            object[] results = this.Invoke("GetBinInfoByCode", new object[] {
                        bincode});
            return ((TWmsBins)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBinInfoByCode(string bincode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBinInfoByCode", new object[] {
                        bincode}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBins EndGetBinInfoByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBins)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BinList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBins[] BinList(short branchid, short bintype) {
            object[] results = this.Invoke("BinList", new object[] {
                        branchid,
                        bintype});
            return ((TWmsBins[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBinList(short branchid, short bintype, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BinList", new object[] {
                        branchid,
                        bintype}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBins[] EndBinList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBins[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewWmsTransTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long NewWmsTransTask(TwmsTrans newtrans) {
            object[] results = this.Invoke("NewWmsTransTask", new object[] {
                        newtrans});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginNewWmsTransTask(TwmsTrans newtrans, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("NewWmsTransTask", new object[] {
                        newtrans}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndNewWmsTransTask(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/testNewWmsTransTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long testNewWmsTransTask() {
            object[] results = this.Invoke("testNewWmsTransTask", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegintestNewWmsTransTask(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("testNewWmsTransTask", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndtestNewWmsTransTask(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TwmsTrans[] GetTransList(short compid, short branchid, short status, int wmstranstypeid) {
            object[] results = this.Invoke("GetTransList", new object[] {
                        compid,
                        branchid,
                        status,
                        wmstranstypeid});
            return ((TwmsTrans[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransList(short compid, short branchid, short status, int wmstranstypeid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransList", new object[] {
                        compid,
                        branchid,
                        status,
                        wmstranstypeid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TwmsTrans[] EndGetTransList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TwmsTrans[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveInternal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long MoveInternal(TWmsBinItemsQty binitemqty, TWmsBinStoretrans thistrans) {
            object[] results = this.Invoke("MoveInternal", new object[] {
                        binitemqty,
                        thistrans});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMoveInternal(TWmsBinItemsQty binitemqty, TWmsBinStoretrans thistrans, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MoveInternal", new object[] {
                        binitemqty,
                        thistrans}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndMoveInternal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransTypeInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsTransTypes TransTypeInfo(int transtypeid) {
            object[] results = this.Invoke("TransTypeInfo", new object[] {
                        transtypeid});
            return ((TWmsTransTypes)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransTypeInfo(int transtypeid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransTypeInfo", new object[] {
                        transtypeid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsTransTypes EndTransTypeInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsTransTypes)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransTypeInfoFromWmsTrans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsTransTypes GetTransTypeInfoFromWmsTrans(int wmstransid) {
            object[] results = this.Invoke("GetTransTypeInfoFromWmsTrans", new object[] {
                        wmstransid});
            return ((TWmsTransTypes)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransTypeInfoFromWmsTrans(int wmstransid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransTypeInfoFromWmsTrans", new object[] {
                        wmstransid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsTransTypes EndGetTransTypeInfoFromWmsTrans(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsTransTypes)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoreTransList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBinStoretrans[] GetStoreTransList(long wmstransid) {
            object[] results = this.Invoke("GetStoreTransList", new object[] {
                        wmstransid});
            return ((TWmsBinStoretrans[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreTransList(long wmstransid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreTransList", new object[] {
                        wmstransid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBinStoretrans[] EndGetStoreTransList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBinStoretrans[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoreTransRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBinStoretrans GetStoreTransRecord(long storetransid) {
            object[] results = this.Invoke("GetStoreTransRecord", new object[] {
                        storetransid});
            return ((TWmsBinStoretrans)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreTransRecord(long storetransid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreTransRecord", new object[] {
                        storetransid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBinStoretrans EndGetStoreTransRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBinStoretrans)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBinItemQtyRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TWmsBinItemsQty GetBinItemQtyRecord(long orderdtlid) {
            object[] results = this.Invoke("GetBinItemQtyRecord", new object[] {
                        orderdtlid});
            return ((TWmsBinItemsQty)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBinItemQtyRecord(long orderdtlid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBinItemQtyRecord", new object[] {
                        orderdtlid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TWmsBinItemsQty EndGetBinItemQtyRecord(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TWmsBinItemsQty)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TOrderDetails GetOrderDetail(long orderdtlid) {
            object[] results = this.Invoke("GetOrderDetail", new object[] {
                        orderdtlid});
            return ((TOrderDetails)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrderDetail(long orderdtlid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrderDetail", new object[] {
                        orderdtlid}, callback, asyncState);
        }
        
        /// <remarks/>
        public TOrderDetails EndGetOrderDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TOrderDetails)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteWmsTranList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long DeleteWmsTranList(long wmstranid) {
            object[] results = this.Invoke("DeleteWmsTranList", new object[] {
                        wmstranid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeleteWmsTranList(long wmstranid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeleteWmsTranList", new object[] {
                        wmstranid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndDeleteWmsTranList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTransListCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetTransListCount(long wmstranid) {
            object[] results = this.Invoke("GetTransListCount", new object[] {
                        wmstranid});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTransListCount(long wmstranid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTransListCount", new object[] {
                        wmstranid}, callback, asyncState);
        }
        
        /// <remarks/>
        public long EndGetTransListCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemByCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TItems GetItemByCode(string itemcode) {
            object[] results = this.Invoke("GetItemByCode", new object[] {
                        itemcode});
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemByCode(string itemcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemByCode", new object[] {
                        itemcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public TItems EndGetItemByCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TItems)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sqlerrorlog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long Sqlerrorlog() {
            object[] results = this.Invoke("Sqlerrorlog", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSqlerrorlog(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Sqlerrorlog", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndSqlerrorlog(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TWmsBinItemsQty {
        
        private long binstoretransidField;
        
        private long binitemsqtyidField;
        
        private short compidField;
        
        private short branchidField;
        
        private long whbinidField;
        
        private long whbinidtoField;
        
        private long wmstransidField;
        
        private short whbintypeField;
        
        private string whbincodeField;
        
        private long itemidField;
        
        private long itemlotidField;
        
        private decimal oldqtyField;
        
        private decimal itemqtyprimaryField;
        
        private short munitprimaryField;
        
        private int deleteRecordField;
        
        private string munitprimarydescField;
        
        private decimal munitsrelationField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        private short munitsecondaryField;
        
        private string munitsecondarydescField;
        
        private decimal itemqtysecondaryField;
        
        private decimal packitemqtyField;
        
        private long orderdtlidField;
        
        private long orderidField;
        
        private long routeidField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private bool updateonlyField;
        
        private string dbrecmoddateField;
        
        private int dbrecmoduserField;
        
        private short transtypeField;
        
        private short transexField;
        
        private bool createbintransrecordField;
        
        private string commentsField;
        
        private string itemcodeField;
        
        private string customertitleField;
        
        private string ordercodeField;
        
        private string itemdescField;
        
        private bool checkavailabilityField;
        
        /// <remarks/>
        public long binstoretransid {
            get {
                return this.binstoretransidField;
            }
            set {
                this.binstoretransidField = value;
            }
        }
        
        /// <remarks/>
        public long binitemsqtyid {
            get {
                return this.binitemsqtyidField;
            }
            set {
                this.binitemsqtyidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public long whbinid {
            get {
                return this.whbinidField;
            }
            set {
                this.whbinidField = value;
            }
        }
        
        /// <remarks/>
        public long whbinidto {
            get {
                return this.whbinidtoField;
            }
            set {
                this.whbinidtoField = value;
            }
        }
        
        /// <remarks/>
        public long wmstransid {
            get {
                return this.wmstransidField;
            }
            set {
                this.wmstransidField = value;
            }
        }
        
        /// <remarks/>
        public short whbintype {
            get {
                return this.whbintypeField;
            }
            set {
                this.whbintypeField = value;
            }
        }
        
        /// <remarks/>
        public string whbincode {
            get {
                return this.whbincodeField;
            }
            set {
                this.whbincodeField = value;
            }
        }
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public long itemlotid {
            get {
                return this.itemlotidField;
            }
            set {
                this.itemlotidField = value;
            }
        }
        
        /// <remarks/>
        public decimal oldqty {
            get {
                return this.oldqtyField;
            }
            set {
                this.oldqtyField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyprimary {
            get {
                return this.itemqtyprimaryField;
            }
            set {
                this.itemqtyprimaryField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public int DeleteRecord {
            get {
                return this.deleteRecordField;
            }
            set {
                this.deleteRecordField = value;
            }
        }
        
        /// <remarks/>
        public string munitprimarydesc {
            get {
                return this.munitprimarydescField;
            }
            set {
                this.munitprimarydescField = value;
            }
        }
        
        /// <remarks/>
        public decimal munitsrelation {
            get {
                return this.munitsrelationField;
            }
            set {
                this.munitsrelationField = value;
            }
        }
        
        /// <remarks/>
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string munitsecondarydesc {
            get {
                return this.munitsecondarydescField;
            }
            set {
                this.munitsecondarydescField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtysecondary {
            get {
                return this.itemqtysecondaryField;
            }
            set {
                this.itemqtysecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal packitemqty {
            get {
                return this.packitemqtyField;
            }
            set {
                this.packitemqtyField = value;
            }
        }
        
        /// <remarks/>
        public long orderdtlid {
            get {
                return this.orderdtlidField;
            }
            set {
                this.orderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public long orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        public long routeid {
            get {
                return this.routeidField;
            }
            set {
                this.routeidField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public bool updateonly {
            get {
                return this.updateonlyField;
            }
            set {
                this.updateonlyField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmoddate {
            get {
                return this.dbrecmoddateField;
            }
            set {
                this.dbrecmoddateField = value;
            }
        }
        
        /// <remarks/>
        public int dbrecmoduser {
            get {
                return this.dbrecmoduserField;
            }
            set {
                this.dbrecmoduserField = value;
            }
        }
        
        /// <remarks/>
        public short transtype {
            get {
                return this.transtypeField;
            }
            set {
                this.transtypeField = value;
            }
        }
        
        /// <remarks/>
        public short transex {
            get {
                return this.transexField;
            }
            set {
                this.transexField = value;
            }
        }
        
        /// <remarks/>
        public bool createbintransrecord {
            get {
                return this.createbintransrecordField;
            }
            set {
                this.createbintransrecordField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string customertitle {
            get {
                return this.customertitleField;
            }
            set {
                this.customertitleField = value;
            }
        }
        
        /// <remarks/>
        public string ordercode {
            get {
                return this.ordercodeField;
            }
            set {
                this.ordercodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public bool checkavailability {
            get {
                return this.checkavailabilityField;
            }
            set {
                this.checkavailabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TItems {
        
        private long itemidField;
        
        private short compidField;
        
        private string itemcodeField;
        
        private long productidField;
        
        private string itemdescField;
        
        private short munitprimaryField;
        
        private short munitsecondaryField;
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public long productid {
            get {
                return this.productidField;
            }
            set {
                this.productidField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TOrderDetails {
        
        private long orderdtlidField;
        
        private short compidField;
        
        private short branchidField;
        
        private long orderidField;
        
        private long itemidField;
        
        private decimal itemqtyprimaryField;
        
        private short munitprimaryField;
        
        private decimal itemqtysecondaryField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        private short munitsecondaryField;
        
        private short orderdtlstatusField;
        
        private string orderdtlcommentsField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private string itemcodeField;
        
        private string itemdescField;
        
        private short munitdecimalsField;
        
        private long customeridField;
        
        private string customertitleField;
        
        private string munitprimarydescField;
        
        private string munitsecondarydescField;
        
        /// <remarks/>
        public long orderdtlid {
            get {
                return this.orderdtlidField;
            }
            set {
                this.orderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public long orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyprimary {
            get {
                return this.itemqtyprimaryField;
            }
            set {
                this.itemqtyprimaryField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtysecondary {
            get {
                return this.itemqtysecondaryField;
            }
            set {
                this.itemqtysecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public short orderdtlstatus {
            get {
                return this.orderdtlstatusField;
            }
            set {
                this.orderdtlstatusField = value;
            }
        }
        
        /// <remarks/>
        public string orderdtlcomments {
            get {
                return this.orderdtlcommentsField;
            }
            set {
                this.orderdtlcommentsField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public string itemcode {
            get {
                return this.itemcodeField;
            }
            set {
                this.itemcodeField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public short munitdecimals {
            get {
                return this.munitdecimalsField;
            }
            set {
                this.munitdecimalsField = value;
            }
        }
        
        /// <remarks/>
        public long customerid {
            get {
                return this.customeridField;
            }
            set {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        public string customertitle {
            get {
                return this.customertitleField;
            }
            set {
                this.customertitleField = value;
            }
        }
        
        /// <remarks/>
        public string munitprimarydesc {
            get {
                return this.munitprimarydescField;
            }
            set {
                this.munitprimarydescField = value;
            }
        }
        
        /// <remarks/>
        public string munitsecondarydesc {
            get {
                return this.munitsecondarydescField;
            }
            set {
                this.munitsecondarydescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TWmsTransTypes {
        
        private int wmstranstypeidField;
        
        private string wmstranstypedescField;
        
        private string wmstranstypeenField;
        
        private short transexField;
        
        private int wmsbindefaultField;
        
        private bool wmsinternaltransField;
        
        private int wmsbinfromField;
        
        private int wmsbintoField;
        
        private bool showbinqtysField;
        
        private bool showallbinsField;
        
        /// <remarks/>
        public int wmstranstypeid {
            get {
                return this.wmstranstypeidField;
            }
            set {
                this.wmstranstypeidField = value;
            }
        }
        
        /// <remarks/>
        public string wmstranstypedesc {
            get {
                return this.wmstranstypedescField;
            }
            set {
                this.wmstranstypedescField = value;
            }
        }
        
        /// <remarks/>
        public string wmstranstypeen {
            get {
                return this.wmstranstypeenField;
            }
            set {
                this.wmstranstypeenField = value;
            }
        }
        
        /// <remarks/>
        public short transex {
            get {
                return this.transexField;
            }
            set {
                this.transexField = value;
            }
        }
        
        /// <remarks/>
        public int wmsbindefault {
            get {
                return this.wmsbindefaultField;
            }
            set {
                this.wmsbindefaultField = value;
            }
        }
        
        /// <remarks/>
        public bool wmsinternaltrans {
            get {
                return this.wmsinternaltransField;
            }
            set {
                this.wmsinternaltransField = value;
            }
        }
        
        /// <remarks/>
        public int wmsbinfrom {
            get {
                return this.wmsbinfromField;
            }
            set {
                this.wmsbinfromField = value;
            }
        }
        
        /// <remarks/>
        public int wmsbinto {
            get {
                return this.wmsbintoField;
            }
            set {
                this.wmsbintoField = value;
            }
        }
        
        /// <remarks/>
        public bool showbinqtys {
            get {
                return this.showbinqtysField;
            }
            set {
                this.showbinqtysField = value;
            }
        }
        
        /// <remarks/>
        public bool showallbins {
            get {
                return this.showallbinsField;
            }
            set {
                this.showallbinsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TWmsBinStoretrans {
        
        private long binstoretransidField;
        
        private long whbinidField;
        
        private short wmstranstypeField;
        
        private long itemidField;
        
        private decimal itemqtyprimaryField;
        
        private decimal oldqtyField;
        
        private long wmstransidField;
        
        private short munitprimaryField;
        
        private long orderidField;
        
        private long orderdtlidField;
        
        private int deleteRecordField;
        
        private short transexField;
        
        private string terminalField;
        
        private decimal itemqtysecondaryField;
        
        private decimal widthField;
        
        private decimal lengthField;
        
        private string customertitleField;
        
        private string itemdescField;
        
        private short munitsecondaryField;
        
        private string wmstransdateField;
        
        private string whbincodeField;
        
        private long whbinidfromField;
        
        private long whbinidtoField;
        
        private short compidField;
        
        private short branchidField;
        
        private string dbreccreatedateField;
        
        private int dbreccreateuserField;
        
        private string dbrecmoddateField;
        
        private int dbrecmoduserField;
        
        /// <remarks/>
        public long binstoretransid {
            get {
                return this.binstoretransidField;
            }
            set {
                this.binstoretransidField = value;
            }
        }
        
        /// <remarks/>
        public long whbinid {
            get {
                return this.whbinidField;
            }
            set {
                this.whbinidField = value;
            }
        }
        
        /// <remarks/>
        public short wmstranstype {
            get {
                return this.wmstranstypeField;
            }
            set {
                this.wmstranstypeField = value;
            }
        }
        
        /// <remarks/>
        public long itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtyprimary {
            get {
                return this.itemqtyprimaryField;
            }
            set {
                this.itemqtyprimaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal oldqty {
            get {
                return this.oldqtyField;
            }
            set {
                this.oldqtyField = value;
            }
        }
        
        /// <remarks/>
        public long wmstransid {
            get {
                return this.wmstransidField;
            }
            set {
                this.wmstransidField = value;
            }
        }
        
        /// <remarks/>
        public short munitprimary {
            get {
                return this.munitprimaryField;
            }
            set {
                this.munitprimaryField = value;
            }
        }
        
        /// <remarks/>
        public long orderid {
            get {
                return this.orderidField;
            }
            set {
                this.orderidField = value;
            }
        }
        
        /// <remarks/>
        public long orderdtlid {
            get {
                return this.orderdtlidField;
            }
            set {
                this.orderdtlidField = value;
            }
        }
        
        /// <remarks/>
        public int DeleteRecord {
            get {
                return this.deleteRecordField;
            }
            set {
                this.deleteRecordField = value;
            }
        }
        
        /// <remarks/>
        public short transex {
            get {
                return this.transexField;
            }
            set {
                this.transexField = value;
            }
        }
        
        /// <remarks/>
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        public decimal itemqtysecondary {
            get {
                return this.itemqtysecondaryField;
            }
            set {
                this.itemqtysecondaryField = value;
            }
        }
        
        /// <remarks/>
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public decimal length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string customertitle {
            get {
                return this.customertitleField;
            }
            set {
                this.customertitleField = value;
            }
        }
        
        /// <remarks/>
        public string itemdesc {
            get {
                return this.itemdescField;
            }
            set {
                this.itemdescField = value;
            }
        }
        
        /// <remarks/>
        public short munitsecondary {
            get {
                return this.munitsecondaryField;
            }
            set {
                this.munitsecondaryField = value;
            }
        }
        
        /// <remarks/>
        public string wmstransdate {
            get {
                return this.wmstransdateField;
            }
            set {
                this.wmstransdateField = value;
            }
        }
        
        /// <remarks/>
        public string whbincode {
            get {
                return this.whbincodeField;
            }
            set {
                this.whbincodeField = value;
            }
        }
        
        /// <remarks/>
        public long whbinidfrom {
            get {
                return this.whbinidfromField;
            }
            set {
                this.whbinidfromField = value;
            }
        }
        
        /// <remarks/>
        public long whbinidto {
            get {
                return this.whbinidtoField;
            }
            set {
                this.whbinidtoField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public string dbreccreatedate {
            get {
                return this.dbreccreatedateField;
            }
            set {
                this.dbreccreatedateField = value;
            }
        }
        
        /// <remarks/>
        public int dbreccreateuser {
            get {
                return this.dbreccreateuserField;
            }
            set {
                this.dbreccreateuserField = value;
            }
        }
        
        /// <remarks/>
        public string dbrecmoddate {
            get {
                return this.dbrecmoddateField;
            }
            set {
                this.dbrecmoddateField = value;
            }
        }
        
        /// <remarks/>
        public int dbrecmoduser {
            get {
                return this.dbrecmoduserField;
            }
            set {
                this.dbrecmoduserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TwmsTrans {
        
        private short compidField;
        
        private short branchidField;
        
        private long wmstransidField;
        
        private long useridField;
        
        private long wmstranstypeidField;
        
        private string wmstransdateField;
        
        private string commentsField;
        
        private short statusField;
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public long wmstransid {
            get {
                return this.wmstransidField;
            }
            set {
                this.wmstransidField = value;
            }
        }
        
        /// <remarks/>
        public long userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public long wmstranstypeid {
            get {
                return this.wmstranstypeidField;
            }
            set {
                this.wmstranstypeidField = value;
            }
        }
        
        /// <remarks/>
        public string wmstransdate {
            get {
                return this.wmstransdateField;
            }
            set {
                this.wmstransdateField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public short status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TWmsBins {
        
        private int whbinidField;
        
        private short compidField;
        
        private short branchidField;
        
        private int whzoneidField;
        
        private string whbincodeField;
        
        private short whbintypeField;
        
        private string friendlycodeField;
        
        /// <remarks/>
        public int whbinid {
            get {
                return this.whbinidField;
            }
            set {
                this.whbinidField = value;
            }
        }
        
        /// <remarks/>
        public short compid {
            get {
                return this.compidField;
            }
            set {
                this.compidField = value;
            }
        }
        
        /// <remarks/>
        public short branchid {
            get {
                return this.branchidField;
            }
            set {
                this.branchidField = value;
            }
        }
        
        /// <remarks/>
        public int whzoneid {
            get {
                return this.whzoneidField;
            }
            set {
                this.whzoneidField = value;
            }
        }
        
        /// <remarks/>
        public string whbincode {
            get {
                return this.whbincodeField;
            }
            set {
                this.whbincodeField = value;
            }
        }
        
        /// <remarks/>
        public short whbintype {
            get {
                return this.whbintypeField;
            }
            set {
                this.whbintypeField = value;
            }
        }
        
        /// <remarks/>
        public string friendlycode {
            get {
                return this.friendlycodeField;
            }
            set {
                this.friendlycodeField = value;
            }
        }
    }
}
