delete from twmsbinitemsqty
delete from twmsbinstoretrans
delete from twmstrans

SELECT * FROM TWMSBINS  WHERE  WHBINID=1

UPDATE TWMSBINITEMSQTY SET WHBINID=1,ITEMID=8881,ITEMQTYPRIMARY= 19.200,ITEMQTYSECONDARY=1,MUNITPRIMARY=1,MUNITSECONDARY=7,ORDERDTLID=8796,WMSTRANSID=12,ORDERID=2028,ROUTEID=NULL,DBRECMODUSER=NULL,DBRECMODDATE=NULL, WHERE WMSTRANSID=12 AND ORDERDTLID = 8796

SELECT ISNULL(COUNT(BINSTORETRANSID),0) FROM twmsbinstoretrans WHERE WMSTRANSID = 12

select * from torderdetails
select * from twmsbinitemsqty
select * from twmsbinstoretrans


DELETE FROM TWMSBINITEMSQTY WHERE WMSTRANSID = 17 AND ORDERDTLID=8796

INSERT INTO TWMSBINITEMSQTY(COMPID,BRANCHID,WHBINID,WMSTRANSID,ITEMID,ITEMQTYPRIMARY,MUNITPRIMARY,ITEMQTYSECONDARY,MUNITSECONDARY,ORDERDTLID,ORDERID,ROUTEID,DBRECCREATEUSER) VALUES(1,1,NULL,17,8881,15.20,1,1,7,8796,2028,NULL,NULL)

SELECT * FROM TWMSBINS 

select TWMSBINSTORETRANS.ORDERDTLID as  orderdtlid,TWMSBINSTORETRANS.MUNITSECONDARY as MUNITSECONDARY,TWMSBINSTORETRANS.ORDERID from twmsbinstoretrans

  SELECT     TWMSBINITEMSQTY.BINITEMSQTYID, TWMSBINITEMSQTY.WHBINID, TWMSBINITEMSQTY.ITEMID, TWMSBINITEMSQTY.WMSTRANSID, TWMSBINITEMSQTY.ITEMQTYPRIMARY,
   TWMSBINITEMSQTY.MUNITPRIMARY, TWMSBINITEMSQTY.ITEMQTYSECONDARY, TWMSBINITEMSQTY.MUNITSECONDARY, TWMSBINITEMSQTY.ORDERDTLID, TWMSBINITEMSQTY.ORDERID,
    TCustomers.CustomerTitle,TServices.ServiceDescription,TItems.ItemDesc 
     FROM         TWMSBINITEMSQTY INNER JOIN TOrderDetails ON TWMSBINITEMSQTY.ORDERDTLID = TOrderDetails.OrderdtlID
      INNER JOINTOrders ON TWMSBINITEMSQTY.ORDERID = TOrders.OrderID INNER JOIN TCustomers ON TOrders.CustomerID = TCustomers.CustomerID INNER JOIN  TServices
   ON TOrderDetails.serviceid = TServices.ServiceID INNER JOIN TItems ON TOrderDetails.ItemID = TItems.ItemID WHERE TWMSBINITEMSQTY.ORDERDTLID = 8796